# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Christopher L. Crawford, PhD
description: >- # this means to ignore newlines until "baseurl:"
  Conservation Scientist.
baseurl: "/" # the subpath of the site
url: "https://chriscra.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
# google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Research
    - name: About
    - name: CV
    # - name: Blog

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: chris [dot] L [dot] crawford [at] gmail.com
      link:  
      # mailto:chris.l.crawford@gmail.com
    - name: Location
      value: Arlington, VA
      link: https://www.google.com/maps/place/Arlington,+VA/

  follow:
    - name: Twitter
      link: http://twitter.com/_chrisLcrawford
      username: "@_chrisLcrawford"
    - name: LinkedIn
      link: http://linkedin.com/in/chriscra
    - name: GitHub
      link: http://github.com/chriscra
    - name: GoogleScholar
      link: https://scholar.google.com/citations?user=Xx6VSpoAAAAJ&hl=en
    - name: Orcid
      link: https://orcid.org/0000-0001-9101-5360
    - name: ResearchGate
      link: https://www.researchgate.net/profile/Christopher-Crawford-10



# # Site Author
# author:
#   name             : "Christopher L. Crawford"
#   avatar           : "profile.png"
#   bio              : "Conservation Scientist"
#   location         : "Philadelphia, PA"
#   employer         :
#   pubmed           :
#   orcid            : "https://orcid.org/0000-0001-9101-5360"
#   googlescholar    : "https://scholar.google.com/citations?user=Xx6VSpoAAAAJ&hl=en"
#   email            : "chris.l.crawford@gmail.com"
#   researchgate     :  # example: "https://www.researchgate.net/profile/Christopher-Crawford-10"
#   github           : "chriscra"
#   linkedin         : "chriscra"
#   stackoverflow    : #"https://stackoverflow.com/users/16409872/christopher-l-crawford"
#   twitter          : "_chrisLcrawford"


# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
